CREATE TABLE `business_fit_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`industryBackground` text,
	`coreSkills` text,
	`leadershipYears` int,
	`teamSizeManaged` varchar(64),
	`preferredIndustries` text,
	`avoidIndustries` text,
	`preferredLocation` varchar(256),
	`willingToRelocate` boolean DEFAULT false,
	`targetRevenue` varchar(64),
	`targetEbitda` varchar(64),
	`preferredDealSize` varchar(64),
	`ownerInvolvement` varchar(64),
	`riskTolerance` enum('conservative','moderate','growth') DEFAULT 'moderate',
	`workHoursPerWeek` int,
	`timelineToClose` varchar(64),
	`whyAcquiring` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `business_fit_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `client_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fullName` varchar(256),
	`email` varchar(320),
	`phone` varchar(32),
	`location` varchar(128),
	`avgAnnualIncome` decimal(12,2),
	`yearsAtIncome` int,
	`redundancyDate` varchar(32),
	`redundancyPayout` decimal(12,2),
	`cashSavings` decimal(12,2),
	`superBalance` decimal(12,2),
	`propertyEquity` decimal(12,2),
	`otherAssets` decimal(12,2),
	`totalLiabilities` decimal(12,2),
	`monthlyLivingExpenses` decimal(10,2),
	`dependants` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `client_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deal_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`dealName` varchar(256),
	`businessType` varchar(128),
	`industry` varchar(128),
	`annualRevenue` decimal(14,2),
	`grossProfit` decimal(14,2),
	`ebitda` decimal(14,2),
	`sde` decimal(14,2),
	`ownerSalaryAddback` decimal(12,2),
	`multipleUsed` decimal(5,2),
	`askingPrice` decimal(14,2),
	`negotiatedPrice` decimal(14,2),
	`depositPercent` decimal(5,2),
	`depositAmount` decimal(12,2),
	`bankLoanAmount` decimal(14,2),
	`sellerFinanceAmount` decimal(12,2),
	`sellerFinanceTerm` int,
	`sellerFinanceRate` decimal(5,2),
	`loanTerm` int,
	`interestRate` decimal(5,2),
	`annualDebtService` decimal(12,2),
	`dscr` decimal(5,2),
	`workingCapitalRequired` decimal(12,2),
	`notes` text,
	`status` enum('draft','active','closed','passed') DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deal_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `resources` (
	`id` int AUTO_INCREMENT NOT NULL,
	`category` varchar(64) NOT NULL,
	`title` varchar(256) NOT NULL,
	`description` text,
	`url` text NOT NULL,
	`isExternal` boolean DEFAULT true,
	`isPinned` boolean DEFAULT false,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `resources_id` PRIMARY KEY(`id`)
);
